### ISSUE TITLE
CLI option for kubeconfig context

### ISSUE THREAD

**Issue by thriqon** [davidB/kubectl-view-allocations#111]
In our environment, we have multiple clusters configured in one `.kube/config` file. Currently, `kubectl-view-allocations` can only use the default one. It would help me a lot if `kubectl-view-allocations` supported a switch `--context test`, similar to `kubectl`.

**Comment by davidB** [comment]
The version 0.11.0 includes `--context` but I was not able to test it, can you tell me if it works or not.

Thanks.

**Comment by thriqon** [comment]
It works, thanks a lot! That was really fast work, I'm seriously impressed!
