### ISSUE TITLE
Public methods & structs

### ISSUE THREAD

**Issue by deepu105** [davidB/kubectl-view-allocations#128]
Any plans to make the main methods and structs into public API so that this lib can be used as a library. I was trying to do something similar for https://github.com/kdash-rs/kdash and found this. I was hoping to use some of the functions from this instead of recoding it

**Comment by davidB** [comment]
Sorry I didn't see the notification of the message. Yes I can definitly make stuff public

**Comment by deepu105** [comment]
That would be super cool

**Comment by davidB** [comment]
I release 0.14 version. being used as lib is far to be top (no doc,...), so feel free to request any improvement.
https://docs.rs/kubectl-view-allocations/0.14.0/kubectl_view_allocations/

**Comment by deepu105** [comment]
Nice. I'll try to migrate to this in KDash and see if it needs any change. Will you be OK if I submit changes as PR?

**Comment by davidB** [comment]
Yes PR are welcomed.
Anyway you made an impressive work with KDash :clap:

**Comment by deepu105** [comment]
Thanks and right back at you :)

Thanks & Regards,
Deepu
