### ISSUE TITLE
If I use watch, formatting is off

### ISSUE THREAD

**Issue by mercer** [davidB/kubectl-view-allocations#134]
# With watch

![image](https://user-images.githubusercontent.com/95358/119127991-bb1ddd00-ba3d-11eb-98ce-6b88d18ff0af.png)

# Without watch 

`watch kubectl view-allocations -g namespace`

![image](https://user-images.githubusercontent.com/95358/119128037-c8d36280-ba3d-11eb-9f26-ae48d5f7ef91.png)

# Suggestion

Would be nice to have a built-in way to have watch. Don't see an option in help.

![image](https://user-images.githubusercontent.com/95358/119128164-f3bdb680-ba3d-11eb-95a1-b68141b2d49d.png)

**Comment by davidB** [comment]
I guess you invert the title or the screenshot.

**Comment by davidB** [comment]
if the issue is the indentation you can try

```sh
watch --color kubectl view-allocations -g namespace
```
