### ISSUE TITLE
Authentication with provider azure not supported

### ISSUE THREAD

**Issue by adriananeci** [davidB/kubectl-view-allocations#146]
While using Azure OIDC for authenticating to cluster, I'm getting the following error while running the plugin:
 
```
❯ kubectl view-allocations
{"v":0,"name":"kubectl_view_allocations","msg":"failed \ncli: CliOpts { context: None, namespace: None, utilization: false, show_zero: false, resource_name: [], group_by: [resource, node, pod], output: table }\nerror: KubeError { context: \"create the kube client\", source: Kubeconfig(AuthExec(\"Authentication with provider azure not supported\")) }","level":50,"hostname":"Adrian.local","pid":55133,"time":"2021-07-13T12:46:14.374337+00:00","target":"kubectl_view_allocations","line":43,"file":"src/main.rs"}
```

**Comment by yacinelazaar** [comment]
I second this

**Comment by davidB** [comment]
Sorry, it's seems it will not be supported by the underhood lib currently use see discussion at [add support for Azure oidc auth · Issue #501 · kube-rs/kube](https://github.com/kube-rs/kube/issues/501).

At end of discussion a workaround seems to use `kubelogin convert-kubeconfig` ([Azure/kubelogin,](https://github.com/Azure/kubelogin))
