### ISSUE TITLE
arm64 not supported

### ISSUE THREAD

**Issue by berryory** [davidB/kubectl-view-allocations#165]
I saw no package for arm64 arch.
can you share how to build? or please support for arm64.

Thanks

**Comment by mike-dube** [comment]
It would be awesome!

**Comment by davidB** [comment]
I'll search how to modify the build pipeline to generate a arm64 version (if doable).
For which OS (linux or mac) ?

**Comment by berryory** [comment]
> I'll search how to modify the build pipeline to generate a arm64 version (if doable). For which OS (linux or mac) ?

MacOS M1, let me know if you need help.

**Comment by davidB** [comment]
Can you try the https://github.com/davidB/kubectl-view-allocations/releases/download/0.14.7-dev/kubectl-view-allocations_0.14.7-dev-aarch64-apple-darwin.tar.gz ?

**Comment by mike-dube** [comment]
I just tried on my M1 :) Seems to work perfectly!

**Comment by davidB** [comment]
Thank for you quick response,
So I'll prepare a release with few updates (dependencies,...)

**Comment by davidB** [comment]
FIX by  #168

**Comment by mike-dube** [comment]
Thanks for the release! For your information, the plugin did not reach Krew, but I got no idea how to gets updated to their repository.

**Comment by davidB** [comment]
Yes I got an issue with the packaging for krew, so I released 0.14.8 and I just resubmit the update on krew-index (pending)
