### ISSUE TITLE
pods not showing if they don't have any requests/limits

### ISSUE THREAD

**Issue by ahmetb** [davidB/kubectl-view-allocations#201]
When I run ` view-allocations -r memory` or ` view-allocations -r cpu` the output list of pods don't contain the pods lacking both cpu/memory requests/limits

If they have one of the limits of requests set, they show up in the list, and the missing column is denoted by `__`:

![image](https://user-images.githubusercontent.com/159209/208578703-50dedaec-d9ec-4fa3-9e00-1c2ef58fc434.png)

I think showing all pods even if they dont have requests/limits set for that particular resource would be ideal (as it would help developers which pods aren't setting none of them).

**Comment by davidB** [comment]
Hi,

Did you try the option:

```
    -z, --show-zero
            Show lines with zero requested and zero limit and zero allocatable
```

Or do you suggest that this option should be one by default and so provide an option to turn it off ?

(Maybe same question for utilization ?)

```
    -u, --utilization
            Force to retrieve utilization (for cpu and memory), require to have metrics-server
            https://github.com/kubernetes-sigs/metrics-server
```

**Comment by ahmetb** [comment]
My bad. Did not see the option.
