### ISSUE TITLE
linux/arm64 target missing

### ISSUE THREAD

**Issue by thomasmunoz13** [davidB/kubectl-view-allocations#208]
Hi, 

First thank you for making this, very helpful and I use it daily :)

Would it be possible to add another architecture target for linux/arm64 (as you already did for darwin here https://github.com/davidB/kubectl-view-allocations/issues/165) ?

Thanks a lot in advance !

**Comment by davidB** [comment]
Good idea, I'll search how to update the CI/publish flow to release a pre-built binary for linux arm64.

**Comment by thomasmunoz13** [comment]
Hello, any news on this ?

**Comment by davidB** [comment]
Can you check the version 0.16.3 ?
https://github.com/davidB/kubectl-view-allocations/releases/download/0.16.3/kubectl-view-allocations_0.16.3-aarch64-unknown-linux-musl.tar.gz

**Comment by thomasmunoz13** [comment]
Hi, thanks for taking care of this :)

The binary is working in my environment (so I'll say it is compatible) but this 0.16.3 is still not available in krew (from what I understand it's missing an update here https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/view-allocations.yaml).

**Comment by davidB** [comment]
Thanks for the confirmation, sorry for delay.
I'll make the PR to update krew later this week.

**Comment by davidB** [comment]
It's now available on krew
