### ISSUE TITLE
Certificate Errors when using

### ISSUE THREAD

**Issue by jed-t5417** [davidB/kubectl-view-allocations#220]
Using against internal lab. Unclear whether this is failing due to certificates used in this plugin, or if it doesnt like the certificates used in the lab which will be self signed.

kubectl view-allocations -g resource
2023-06-01T15:21:28.377339Z ERROR failed with error error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain
Error: 
   0: Failed to list nodes
   1: HyperError: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain
   2: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain
   3: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain
   4: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:
   5: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:

Location:
   src/main.rs:47

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

kubectl view-allocations -u         
2023-06-01T15:22:42.695887Z ERROR failed with error error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain
Error: 
   0: Failed to list nodes
   1: HyperError: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain
   2: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain
   3: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: self signed certificate in certificate chain
   4: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:
   5: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:

Location:
   src/main.rs:47

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by robinkb** [comment]
I'm seeing this issue as well when running the latest version on Fedora Linux 38. I manually downloaded version 0.15.1, and that works fine.

(Love the plugin by the way, super useful)

**Comment by byroncollins** [comment]
I'm seeing this issue from the Windows 0.16.3 x86_64 version as well and downloading the previous version of 0.15.1 fixes my issue as well. The difference is however that our certificates are public and trusted.

**Comment by davidB** [comment]
Can you give a try to version 0.17.x ?

(since version 0.17, the handling of SSL move from OpenSSL to rustls + few other bugfix on the underling kube library).
