### ISSUE TITLE
darwin arm64 system is not supported 

### ISSUE THREAD

**Issue by yeah334** [davidB/kubectl-view-allocations#223]
![image](https://github.com/davidB/kubectl-view-allocations/assets/72294220/120b2919-87d7-46ab-8f03-43b04368e3b0)

**Comment by davidB** [comment]
How to install the tools? It's to fix the path as the version is for arm64 is available: https://github.com/davidB/kubectl-view-allocations/releases/tag/0.16.3

**Comment by davidB** [comment]
The installation script via curl is updated to also manage darwin arm64.

Thanks for reporting, feel free to reopen if the issue is not resolved.
