### ISSUE TITLE
Add support json output

### ISSUE THREAD

**Issue by jeffcouch21** [davidB/kubectl-view-allocations#62]
This goes along with CSV output, the need has come up for us to track object allocations over time in json format. This would also allow for the timestamp data to be reported only once in the document. It will also allow for other descriptive data about the hierarchy to be included, including labels on the object (node, pod, namespace) in question.

**Comment by davidB** [comment]
Why not use the k8s server api in this case ?

**Comment by davidB** [comment]
no response, I close the ticket.
feel free to re-open to continue the discussion/request
