### ISSUE TITLE
Bug - The cluster total requested and memory limit are displayed in Ki

### ISSUE THREAD

**Issue by j-martin** [davidB/kubectl-view-allocations#63]
Instead of Mi, Gi like every sub-totals per nodes.

```
...
  memory                                                                74249595.0Ki         64%  105203067.0Ki     90%      111.2Gi  10.9Gi
  ├─ gke-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   19562.8Mi         69%      29958.8Mi    105%       27.8Gi     0.0
...

```

Neat tool btw!

**Comment by davidB** [comment]
currently the "unit" for total is the lower unit the group to keep the accuracy, because the rounding caused more trouble (see #8). But I'm open to a better proposal.

**Comment by j-martin** [comment]
My answer to https://github.com/davidB/kubectl-view-allocations/issues/8#issuecomment-559238627

I would round up to the first decimal.

1300 displayed as "1k" or "2k" ? => 1.3Ki
1500 displayed as "1k" or "2k" ? => 1.5Ki
1700 displayed as "1k" or "2k" ? => 1.7Ki 

For example `74249595.0Ki => 70.8Gi`. 

To me having a super accurate sum is less important than a more human-readable one. I am assuming the summations are done in bytes and the human-readable unit formatted at render time.

If I read #8 properly, would it make sense to have a different unit "formatter" for CPU and memory (to avoid the said issue)?

Would it make sense to add a flag to force the sums to be displayed with the biggest reasonable unit for the table output? Arguably it may not be necessary because I would assume that anybody that cares about precision for automation (? or something else) would use the CSV output which uses bytes (as it should).

**Comment by davidB** [comment]
Hi,

The version 0.9.1 (from today) adjust scale/unit on every columns with the default display (non json).
close the ticket if ok for you

**Comment by j-martin** [comment]
Confirming the "bug" is fixed. Thanks!
