### ISSUE TITLE
Keep Gi when outputting csv

### ISSUE THREAD

**Issue by yashbhutwala** [davidB/kubectl-view-allocations#86]
Is it possible to keep Gi when outputting to csv?

**Comment by davidB** [comment]
No, the goal of csv is to be processed by machine. Processing unit like Ki, Gi,... introduce overhead on caller side (I remember the time I spend to find a "right" way to parse value and unit.

Sorry, I miss the notification for this request

**Comment by yashbhutwala** [comment]
Darn!  I was hoping to use the csv as a human 👨‍🍳, but if it's too much hassle, then we can close this 👍.  Thanks for the response @davidB 😄 💯
